baseURL = "https://julian-englert.netlify.app/"
languageCode = "en-us"
title = "JU EN"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Julian Englert"

[params]
   author = "Julian Englert"
   description = "Anubis is a simple minimalist theme for Hugo blog engine."
   dateFormat = "2006-01-02"
   paginationSinglePost = true
   style = "light-without-switcher"
   readMore = false

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params.staticman]
    endpoint = "https://hugo-staticman-comments.herokuapp.com/v2/entry"
    username = "julian-englert"
    repository = "blog"
    branch = "master"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true